### ISSUE TITLE
Add command `desuki create api <app-name>`

### ISSUE THREAD

**Issue by HallexCosta** [HallexCosta/desuki-cli#2]
### Overview

You must define which requirements to run the command `desuki create api <app-name>`

### Tasks

- [ ] The fourth param must define the name of app.
  - example: `desuki create api node-server-be-a-savior`.
- [ ] If an application name is declared, fill env var `APP_NAME` with value, otherwise keep the default name *"server"*.
- [ ] The command `desuki create api <app-name>` must be a flag `--help`, `--with-typescript`.
- [ ] Add flag `--model` alias `-m` to define model of project
  - example: `desuki create api node-api-solid -m sod`
  - sod means Single Responsibility, Open-Close, Dependency Inversion.
- [ ] Add alias to flags `--help` to `-h` and `--with-typescript` to `-wt`.
- [ ] Must be clone repository the `hallexcosta/node-api-boilerplate` from Github.
- [ ] Show message that repository was cloned successfully.
- [ ] Remove `.git` folder after clone boilerplate repository.
- [ ] Create `.env` file following env model.

### Env Model

```sh
# NAME FROM APP
APP_NAME=name-of-app

# PORT
PORT=3333

# Envrionment that app run (use test, development or production)
NODE_ENV=production

# ELEPHANT API KEY (fill this vars if to use elephantsql.com)
ELEPHANT_API_KEY=
ELEPHANT_INSTANCE_NAME=

# DATABASE LOGIN
DB_TYPE=
DB_HOST=
DB_PORT=
DB_USERNAME=
DB_PASSWORD=
DB_NAME=

# Express (optional)
DEBUG=true
```
