### ISSUE TITLE
Add command `desuki create web <app-name>`

### ISSUE THREAD

**Issue by HallexCosta** [HallexCosta/desuki-cli#4]
### Overview

You must define which requirements to run the command `desuki create web <app-name>`

### Tasks

- [ ] The fourth param must define the name of the app.
  - For example: `desuki create web webapp-be-a-savior`.
- [ ] If an application name is declared, fill env var `APP_NAME` with value, otherwise keep the default name *"web"*.
- [ ] The command `desuki create api <app-name>` must be a flag `--help`, `--with-typescript`.
- [ ] Add flag `--model` alias `-m` to define model of project
- [ ] Add alias to flags `--help` to `-h` and `--with-typescript` to `-wt`.
- [ ] Must be clone repository the `hallancosta/expo-boilerplate` from Github.
- [ ] Show message that repository was cloned successfully.
- [ ] Remove `.git` folder after clone boilerplate repository.
