### ISSUE TITLE
Add commando `desuki create monorepo <app-name>`

### ISSUE THREAD

**Issue by HallexCosta** [HallexCosta/desuki-cli#5]
### Overview

You must define which requirements to run the command `desuki create monorepo`

### Tasks

- [ ] The fourth param must define the name of the app.
  - example: `desuki create monorepo be-a-savior-platforms`.
- [ ] If an application name is declared, fill env var `APP_NAME` with value, otherwise keep the default name *"monorepo"*.
- [ ] The command `desuki create monorepo <app-name>` must be a flag `--help`, `--with-typescript`.
- [ ] Add alias to flags `--help` to `-h` and `--with-typescript` to `-wt`.
- [ ] Must be clone repository the `hallexcosta/node-ecosystem-monorepo` from Github.
- [ ] Show message that repository was cloned successfully.
- [ ] Remove `.git` folder of all packages after cloning monorepo boilerplate.
- [ ] Create `.env` file in folder `{monorepo_name}/packages/server` following env models.

### Env Model

```sh
# NAME FROM APP
APP_NAME=name-of-app

# PORT
PORT=3333

# Envrionment that app run (use test, development or production)
NODE_ENV=production

# ELEPHANT API KEY (fill this vars if to use elephantsql.com)
ELEPHANT_API_KEY=
ELEPHANT_INSTANCE_NAME=

# DATABASE LOGIN
DB_TYPE=
DB_HOST=
DB_PORT=
DB_USERNAME=
DB_PASSWORD=
DB_NAME=

# Express (optional)
DEBUG=true
```
